server:
  port: 9001

spring:
  banner:
    location: banner.txt
    charset: UTF-8
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: ${H2_USER}
    password: ${H2_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  pattern:
    console: '%clr(%-5p) %clr(:){red} %clr(%m){faint}%n'